#!/bin/bash
echo "Installing Swap"
echo ""
echo ""
fallocate -l 5G /swapfile
chown root:root /mnt/swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
cp /etc/fstab /etc/fstab.bak
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
echo " Swap Install"
sudo sysctl vm.swappiness=10
echo "vm.swappiness=10"
sudo sysctl vm.vfs_cache_pressure=50
echo "vm.vfs_cache_pressure=50"
sleep 5
